sudo: false
language: python
cache: pip

matrix:
    fast_finish: true
    include:
      - { python: "3.4", env: DJANGO_VERSION="1.11.*" }
      - { python: "3.4", env: DJANGO_VERSION="2.0.*" }

      - { python: "3.5", env: DJANGO_VERSION="1.11.*" }
      - { python: "3.5", env: DJANGO_VERSION="2.0.*" }
      - { python: "3.5", env: DJANGO_VERSION="2.1.*" }
      - { python: "3.5", env: DJANGO_VERSION="2.2.*" }
      - { python: "3.5", env: DJANGO_VERSION="3.1.*" }
      - { python: "3.5", env: DJANGO_VERSION="3.2.*" }

      - { python: "3.6", env: DJANGO_VERSION="1.11.*" }
      - { python: "3.6", env: DJANGO_VERSION="2.0.*" }
      - { python: "3.6", env: DJANGO_VERSION="2.1.*" }
      - { python: "3.6", env: DJANGO_VERSION="2.2.*" }
      - { python: "3.6", env: DJANGO_VERSION="3.1.*" }
      - { python: "3.6", env: DJANGO_VERSION="3.2.*" }

      - { python: "3.7", env: DJANGO_VERSION="2.2.*", dist: xenial, sudo: true }
      - { python: "3.7", env: DJANGO_VERSION="3.2.*", dist: xenial, sudo: true }

      - { python: "3.8", env: DJANGO_VERSION="2.2.*", dist: xenial, sudo: true }
      - { python: "3.8", env: DJANGO_VERSION="3.2.*", dist: xenial, sudo: true }
      - { python: "3.8", env: DJANGO_VERSION="4.0.*", dist: xenial, sudo: true }

      - { python: "3.9", env: DJANGO_VERSION="3.2.*", dist: xenial, sudo: true }
      - { python: "3.9", env: DJANGO_VERSION="4.0.*", dist: xenial, sudo: true }

install:
    - pip install Django==${DJANGO_VERSION}
    - pip install coverage
    - pip install codacy-coverage

branches:
  only:
    - master

script:
  - coverage run --source=reviews setup.py test

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
