language: python
cache: pip

matrix:
    fast_finish: true
    include:
      - { python: "3.4", env: DJANGO_VERSION="1.11.*" }
      - { python: "3.4", env: DJANGO_VERSION="2.0.*" }

      - { python: "3.5", env: DJANGO_VERSION="1.11.*" }
      - { python: "3.5", env: DJANGO_VERSION="2.0.*" }
      - { python: "3.5", env: DJANGO_VERSION="2.1.*" }
      - { python: "3.5", env: DJANGO_VERSION="2.2.*" }

      - { python: "3.6", env: DJANGO_VERSION="1.11.*" }
      - { python: "3.6", env: DJANGO_VERSION="2.0.*" }
      - { python: "3.6", env: DJANGO_VERSION="2.1.*" }
      - { python: "3.6", env: DJANGO_VERSION="2.2.*" }
      - { python: "3.6", env: DJANGO_VERSION="3.1.*" }
      - { python: "3.6", env: DJANGO_VERSION="3.2.*" }

      - { python: "3.7", env: DJANGO_VERSION="2.2.*" }
      - { python: "3.7", env: DJANGO_VERSION="3.2.*" }

      - { python: "3.8", env: DJANGO_VERSION="2.2.*" }
      - { python: "3.8", env: DJANGO_VERSION="3.2.*" }
      - { python: "3.8", env: DJANGO_VERSION=dev }

      - { python: "3.9", env: DJANGO_VERSION="3.2.*" }
      - { python: "3.9", env: DJANGO_VERSION=dev }

    allow_failures:
      - env: DJANGO_VERSION=dev

install:
    - pip install coverage
    - pip install codacy-coverage
    - if [[ $DJANGO_VERSION == dev ]]; then pip install -e git+https://github.com/django/django@main#egg=django
      -U; else pip install Django==${DJANGO_VERSION} -U; fi

branches:
  only:
    - master

script:
  - coverage run --source=reviews setup.py test

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
